{
 "title": "Thingsboard Integration (statistics)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Integration Common information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Integration start All",
   "type": "graph",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "count" }
   ],
   "targets": [
    {
     "expr": "sum(integration_stats_gauge{name=\"start\"})",
     "legendFormat": "{{type}} {{state}}"
    }
   ]
  },
  {
   "title": "Uplink msg (interval 30s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "$B - $A", "type": "math" },
    { "expression": "$E - $D", "type": "math" }
   ]
  },
  {
   "title": "Downlink msg (interval 30s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "$B - $A", "type": "math" },
    { "expression": "$E - $D", "type": "math" }
   ]
  },
  { "title": "Integration started by state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Integration state  by type  by success",
   "type": "graph",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "integration_stats_gauge{name=\"start\", state=\"success\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Integration state  by type  by failed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "count" }
   ],
   "targets": [
    {
     "expr": "integration_stats_gauge{name=\"start\",state=\"failed\"}",
     "legendFormat": "{{type}} {{state}}"
    }
   ]
  },
  { "title": "Uplink", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Uplink Integration by type by all/success/failed",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 23, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(type) (floor(delta(integration_stats_counter_total{name=\"msgUplink\"}[$__interval])))",
     "legendFormat": "{{type}} All"
    },
    {
     "expr": "floor(delta(integration_stats_counter_total{name=\"msgUplink\"}[$__interval]))",
     "legendFormat": "{{type}} {{state}}"
    }
   ]
  },
  { "title": "Downlink", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Downlink Integration by type by all/success/failed ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(type) (floor(delta(integration_stats_counter_total{name=\"msgDownlink\"}[$__interval])))",
     "legendFormat": "{{type}} All"
    },
    {
     "expr": "floor(delta(integration_stats_counter_total{name=\"msgDownlink\"}[$__interval]))",
     "legendFormat": "{{type}} {{state}}"
    }
   ]
  },
  { "title": "Integration started by process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Integration start  process  by type  by all/success/failed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "cnt" } },
   "targets": [
    { "expression": "$B - $A", "type": "math" },
    { "expression": "$E - $D", "type": "math" }
   ]
  }
 ]
}