{
 "title": "Single Service Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "tb-monolith" }
  ]
 },
 "panels": [
  {
   "title": "Core Producer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(statsName) (increase(core_producer_total{job=\"$job\"}[1m]))",
     "legendFormat": "{{statsName}}"
    }
   ]
  },
  {
   "title": "Transport Producer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(statsName) (increase(transport_producer_total{job=\"$job\"}[1m]))",
     "legendFormat": "{{statsName}}"
    }
   ]
  },
  {
   "title": "Rule Engine Producer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(statsName) (increase(ruleEngine_producer_total{job=\"$job\"}[1m]))",
     "legendFormat": "{{statsName}}"
    }
   ]
  },
  {
   "title": "Core Starts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(statsName) (increase(core_total{job=\"$job\"}[1m]))",
     "legendFormat": "{{statsName}}"
    }
   ]
  },
  {
   "title": "Transport Consumer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(statsName) (increase(transport_total{job=\"$job\"}[1m]))"
    }
   ]
  },
  {
   "title": "[Main] Rule Engine Queue Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(statsName)(increase(ruleEngine_Main_total{job=\"$job\"}[1m]))",
     "legendFormat": "{{statsName}}"
    }
   ]
  },
  {
   "title": "[HighPriority] Rule Engine Queue Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(statsName)(increase(ruleEngine_HighPriority_total{job=\"$job\"}[1m]))",
     "legendFormat": "{{statsName}}"
    }
   ]
  },
  {
   "title": "[SequentialByOriginator] Rule Engine  Queue Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(statsName)(increase(ruleEngine_SequentialByOriginator_total{job=\"$job\"}[1m]))",
     "legendFormat": "{{statsName}}"
    }
   ]
  },
  {
   "title": "JsInvoke Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(statsName) (increase(jsInvoke_total{job=\"$job\"}[1m]))",
     "legendFormat": "{{statsName}}"
    }
   ]
  }
 ]
}